### ISSUE TITLE
avy-goto hangs if there's an image-mode window open

### ISSUE THREAD

**Issue by Malabarba** [abo-abo/avy-jump#1]
1. Split the frame in two windows.
2. Open a text file in one and an image file on the other.
3. Try to `avy-goto-word-1` on the text buffer.

Emacs hangs after I type the leading char.

**Comment by Malabarba** [comment]
I think this happen because image files are very large, and because of how image-mode works, the entire contents of the `image-mode` are contained within in the window boundaries. So, when avy tries to parse the text being displayed, it has to parse a lot of text.

The easiest fix would be to just ignore text inside an `image-mode` buffer, since that's unlikely to ever be useful.

**Comment by Malabarba** [comment]
I didn't test, but it would probably also happen with `docview`.

**Comment by abo-abo** [comment]
Thanks, I've fixed it for a part of the functions (word, char, etc).  Some others still need the same fix. I'll do it a bit later, I'm not in a mood for abstraction today.

**Comment by Malabarba** [comment]
Take your time. :-)  And thanks!
