### ISSUE TITLE
avy-goto-subword-0 isn't very accurate

### ISSUE THREAD

**Issue by tsdh** [abo-abo/avy-jump#4]
Even with my fix from the second commit in #3, `avy-goto-subword-0` isn't too accurate.  With a word like `ThisIsATest`, it considers `This`, `Is`, and `ATest` as subwords.  But of course `ATest` are actually two subwords.

I think a proper fix would be to re-use `subword-forward-regexp` defined in emacs' `subword.el`.  (That also requires `case-fold-seach` to be nil, so my second commit from #3 is correct anyway.)

**Comment by abo-abo** [comment]
> re-use subword-forward-regexp

I could remove the function completely and then just use subword in `avy-goto-word-0` if `subword-mode` is on.  What do you think?

**Comment by tsdh** [comment]
Not sure. If subword-mode is active, then the user has obviously a preference for subword navigation.  OTOH, subword gives many more candidates in e.g. Java buffers and other langs using CamelCaseStyle, and usually you want to jump to the beginning of a method, class, field, or variable in at least 90% of all cases.  So I think I prefer the current behavior.

By the way: I noticed that with `avy-goto-subword-0`, the paths are printed **before** the leading char of the subword.  With `avy-goto-word-0` (and I think with all other avy-jump commands) they are printed **after** the leading char.
